nodeLinker: node-modules

packageExtensions:
  "@glideapps/glide-data-grid@*":
    peerDependencies:
      react: "^16.12.0 || 17.x || 18.x || 19.x"
      react-dom: "^16.12.0 || 17.x || 18.x || 19.x"
